POST http://localhost:4500/project 
Content-Type: application/json

{
    "Title": "Paragraph",
    "Content":"This is A paragraph",
    "CreatedAt":"24/7/2023",
}

###
GET http://localhost:4500/project

###
GET http://localhost:4500/project/ce3f9c1b-28f7-4012-b968-90e5ccba475c
### UPDATING PROJECT
PUT http://localhost:4500/project/2d460c35-2ea7-4289-bc81-4204b53a4696
Content-Type: application/json

{
     "Title": "Heading",
    "Content":"This is A heading",
    "CreatedAt":"2o/9/2022",
}

###
DELETE http://localhost:4500/project/3dbd0bb0-a7e8-49e2-a4fe-1b18cbffc774